# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repeater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('callsign', models.CharField(max_length=128)),
                ('frequency', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
