# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repeaters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repeater',
            options={'ordering': ['callsign']},
        ),
        migrations.RemoveField(
            model_name='repeater',
            name='frequency',
        ),
        migrations.AddField(
            model_name='repeater',
            name='input_frequency',
            field=models.CharField(default='144.000', max_length=128, verbose_name='Input Frequency'),
        ),
        migrations.AddField(
            model_name='repeater',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='repeater',
            name='output_frequency',
            field=models.CharField(blank=True, max_length=128, verbose_name='Output Frequency'),
        ),
        migrations.AlterField(
            model_name='repeater',
            name='callsign',
            field=models.CharField(max_length=128, verbose_name='Repeater Callsign'),
        ),
    ]
