# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import repeaters.models


class Migration(migrations.Migration):

    dependencies = [
        ('repeaters', '0003_repeater_offset'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeaterLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('longitude', models.CharField(blank=True, max_length=64, verbose_name='Longitude')),
                ('latitude', models.CharField(blank=True, max_length=64, verbose_name='Latitude')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='State')),
                ('postal_code', models.CharField(blank=True, max_length=255, verbose_name='Postal Code')),
                ('repeater', models.ForeignKey(on_delete=repeaters.models.Repeater, related_name='repeaters', related_query_name='repeater', to='repeaters.Repeater')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
