# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import repeaters.models


class Migration(migrations.Migration):

    dependencies = [
        ('repeaters', '0004_repeaterlocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeaterDigitalModes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('c4fm', models.BooleanField(default=False, verbose_name='C4FM')),
                ('d_star', models.BooleanField(default=False, verbose_name='D-STAR')),
                ('dmr', models.BooleanField(default=False, verbose_name='DMR')),
                ('repeater', models.ForeignKey(on_delete=repeaters.models.Repeater, related_name='digitalmodes', related_query_name='digitalmode', to='repeaters.Repeater')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepeaterLinkModes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('echolink', models.BooleanField(default=False, verbose_name='EchoLink')),
                ('irlp', models.BooleanField(default=False, verbose_name='IRLP')),
                ('repeater', models.ForeignKey(on_delete=repeaters.models.Repeater, related_name='linkmodes', related_query_name='linkmode', to='repeaters.Repeater')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='repeaterlocation',
            name='repeater',
            field=models.ForeignKey(on_delete=repeaters.models.Repeater, related_name='locations', related_query_name='location', to='repeaters.Repeater'),
        ),
    ]
